package com.beeant.model;

import java.util.Date;

public class TUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_id
     *
     * @mbggenerated Sun Dec 13 12:04:49 CST 2015
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_name
     *
     * @mbggenerated Sun Dec 13 12:04:49 CST 2015
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_birthday
     *
     * @mbggenerated Sun Dec 13 12:04:49 CST 2015
     */
    private Date userBirthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_salary
     *
     * @mbggenerated Sun Dec 13 12:04:49 CST 2015
     */
    private Double userSalary;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_id
     *
     * @return the value of t_user.user_id
     *
     * @mbggenerated Sun Dec 13 12:04:49 CST 2015
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_id
     *
     * @param userId the value for t_user.user_id
     *
     * @mbggenerated Sun Dec 13 12:04:49 CST 2015
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_name
     *
     * @return the value of t_user.user_name
     *
     * @mbggenerated Sun Dec 13 12:04:49 CST 2015
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_name
     *
     * @param userName the value for t_user.user_name
     *
     * @mbggenerated Sun Dec 13 12:04:49 CST 2015
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_birthday
     *
     * @return the value of t_user.user_birthday
     *
     * @mbggenerated Sun Dec 13 12:04:49 CST 2015
     */
    public Date getUserBirthday() {
        return userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_birthday
     *
     * @param userBirthday the value for t_user.user_birthday
     *
     * @mbggenerated Sun Dec 13 12:04:49 CST 2015
     */
    public void setUserBirthday(Date userBirthday) {
        this.userBirthday = userBirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_user.user_salary
     *
     * @return the value of t_user.user_salary
     *
     * @mbggenerated Sun Dec 13 12:04:49 CST 2015
     */
    public Double getUserSalary() {
        return userSalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_user.user_salary
     *
     * @param userSalary the value for t_user.user_salary
     *
     * @mbggenerated Sun Dec 13 12:04:49 CST 2015
     */
    public void setUserSalary(Double userSalary) {
        this.userSalary = userSalary;
    }
}